version: '2'
services:
    casoauth2-postgresql:
        container_name: casoauth2-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/casoauth2/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=casoauth2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
