version: '2'
services:
    casoauth2-postgresql:
        container_name: casoauth2-postgresql
        image: postgres:9.5.4
        hostname: pgdb2
        # volumes:
        #     - ~/volumes/jhipster/casoauth2/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=casoauth2
            - POSTGRES_PASSWORD=casoauth2
        ports:
            - 5932:5432
